---
config:
  theme: redux
  layout: fixed
---
flowchart TB
    A(["Startup"]) --> n1["Lett soglia max,min<br>Tipo di dato:float,not null"]
    n5["Presa campione<br>Tipo di dato:float,not null"] --> n6["campione != errore"]
    n6 -- Vero --> n7["Se campione &lt; soglia max"]
    n7 -- Vero --> n8["campione &gt; Soglia min"]
    n7 -- Falso --> n9["Invio Alert a DB"]
    n8 -- Falso --> n10["Invio Alert a DB"]
    n6 -- Falso --> n12["Invio Alert a DB"]
    n1 --> n14["contatore = 0"]
    n14 --> n13["Contatore != 5"]
    n13 -- Vero --> n4["Lett soglia tempo (umidità)<br>TimeStamp,not null"]
    n13 -- Falso --> n1
    n8 -- vero --> n13
    n10 --> n13
    n9 --> n13
    n12 --> n13
    n4 --> n15["cont= cont+1"]
    n15 --> n5

    n1@{ shape: proc}
    n5@{ shape: proc}
    n6@{ shape: decision}
    n7@{ shape: decision}
    n8@{ shape: decision}
    n9@{ shape: proc}
    n10@{ shape: proc}
    n12@{ shape: proc}
    n14@{ shape: proc}
    n13@{ shape: loop-limit}
    n4@{ shape: proc}
    n15@{ shape: proc}