erDiagram
	direction TB
	APIARIO {
		int api_id PK ""  
		string api_luogo  ""  
		string api_nome  ""  
	}

	ARNIA {
		int arn_id PK ""  
		date arn_dataInst  ""  
		boolean arn_piena  ""  
		int arn_api_id FK ""  
	}

	SENSORE {
		int sen_id PK ""  
		string sen_tipo  ""  
		string sen_stato  ""  
		int sen_arn_id FK ""  
	}

	RILEVAZIONE {
		int ril_id PK ""  
		float ril_dato  ""  
		date ril_data  ""  
		time ril_ora  ""  
		int ril_sen_id FK ""  
	}

	NOTIFICA {
		int not_id PK ""  
		string not_titolo  ""    
		string not_desc  ""   
	}